### ISSUE TITLE
Elasticsearch7 is not supported？

### ISSUE THREAD

**Issue by Gogo-scc** [jlolling/talendcomp_tElasticSearch#23]
Hi ：
I test this on my elasticsearch 7.10，I found this error:
[statistics] connecting to socket on port 3748
[statistics] connected
Exception in component tElasticSearchIndexOutput_1 (amq1)
java.lang.Exception: execute bulk request to servers: [http://172.18.5.10:9200] failed: Elasticsearch exception [type=exception, reason=Content-Type header [application/vnd.elasticsearch+json; compatible-with=7] is not supported]
	at de.jlo.talendcomp.elasticsearch.ElasticClient.executeBulk(ElasticClient.java:229)
	at de.jlo.talendcomp.elasticsearch.IndexOutput.executeBulk(IndexOutput.java:122)
	at de.jlo.talendcomp.elasticsearch.IndexOutput.executeBulkFinal(IndexOutput.java:99)
	at local_project.amq1_0_1.amq1.tRowGenerator_1Process(amq1.java:1551)
	at local_project.amq1_0_1.amq1.runJobInTOS(amq1.java:2269)
	at local_project.amq1_0_1.amq1.main(amq1.java:2118)
Caused by: ElasticsearchStatusException[Elasticsearch exception [type=exception, reason=Content-Type header [application/vnd.elasticsearch+json; compatible-with=7] is not supported]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:620)
	at de.jlo.talendcomp.elasticsearch.ElasticClient.executeBulk(ElasticClient.java:223)
	... 5 more
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://172.18.5.10:9200], URI [/_bulk?timeout=1m], status line [HTTP/1.1 406 Not Acceptable]
{"error":"Content-Type header [application/vnd.elasticsearch+json; compatible-with=7] is not supported","status":406}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
		at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699)
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
		... 9 more
[statistics] disconnected

Doesn't this version support 7?

**Comment by jlolling** [comment]
Indeed. I have developed this component for a customer while version 6 was
the current release. I have not kept track the development since the
customer does lose interest in it.

I personally do not have a use case. I can update these components but a
bit busy at the moment. Do you have interest in continue this development?

Best regards
Jan Lolling

Gogo-scc ***@***.***> schrieb am Mi., 30. Aug. 2023, 07:14:

**Comment by Gogo-scc** [comment]
Okay！ Thank you for open source these components! I just use these components to do some simple testing. Not sure if production environment will be used.I tried using an older version and it seems to work fine！
