### ISSUE TITLE
[No such host is known (https)]

### ISSUE THREAD

**Issue by tzvezdov** [jlolling/talendcomp_tElasticSearch#24]
Hello,

thank you for the component and sharing it with us.

I am not sure if I am doing something wrong but I need help with the establishing connection part. 

**Talend Studio: 7.3.1**

For example: in tELasticSearchRequest / IndexOutput I specify the "Server Nodes" property by providing the host url. Tried with pre-prod environment**(version: 7.17.13)**, tried with Elastic Search running on a docker container locally **(version: 8.11.1)**  . But I am getting always this error: 

`[ERROR]: dwh_bi.test_es_ping2_0_1.test_es_ping2 - Request failed: Request io-error: No such host is known (https)
java.lang.Exception: Request io-error: No such host is known (https)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:69)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.tElasticSearchRequest_1Process(test_es_ping2.java:892)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.runJobInTOS(test_es_ping2.java:1846)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.main(test_es_ping2.java:1602)
Caused by: java.io.IOException: No such host is known (https)
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:937)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:52)
	... 3 more
Caused by: java.net.UnknownHostException: No such host is known (https)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1530)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1520)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	... 5 more
[FATAL]: dwh_bi.test_es_ping2_0_1.test_es_ping2 - tElasticSearchRequest_1 Request io-error: No such host is known (https)
java.lang.Exception: Request io-error: No such host is known (https)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:69)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.tElasticSearchRequest_1Process(test_es_ping2.java:892)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.runJobInTOS(test_es_ping2.java:1846)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.main(test_es_ping2.java:1602)
Caused by: java.io.IOException: No such host is known (https)
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:937)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:52)
	... 3 more
Caused by: java.net.UnknownHostException: No such host is known (https)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1530)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1520)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	... 5 more
Exception in component tElasticSearchRequest_1 (test_es_ping2)
java.lang.Exception: Request io-error: No such host is known (https)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:69)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.tElasticSearchRequest_1Process(test_es_ping2.java:892)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.runJobInTOS(test_es_ping2.java:1846)
	at dwh_bi.test_es_ping2_0_1.test_es_ping2.main(test_es_ping2.java:1602)
Caused by: java.io.IOException: No such host is known (https)
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:937)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
	at de.jlo.talendcomp.elasticsearch.RequestExecuter.performRequest(RequestExecuter.java:52)
	... 3 more
Caused by: java.net.UnknownHostException: No such host is known (https)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1530)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1520)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	... 5 more
[statistics] disconnected
`

Am I doing something wrong? Or is it simply some sort of issue with the component? I tried providing the URL like this: 

Here is a picture of this simple job I created for this purpose -> I just want to ping so that I can incorporate the component in my job (where I want to post docs) but I am getting the same error. 

![image](https://github.com/jlolling/talendcomp_tElasticSearch/assets/106353931/b1e9fe04-a34f-4f87-a7d3-4798c4c9e890)

I tried specifying it as a context variable, using the ip address instead of the name and everything I could think of. It seems that my input host is not even printed to the console it just says "(https)" and nothing more..

Please give me an advice!

Thank you in advance.

**Comment by tzvezdov** [comment]
Just to add a comment that both pre prod and local ES are reachable through Postman
